[package]
name = "tokens"
version = "2.8.4"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "^2.8.4"


[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[lib]
